server:
  port: 8081

logging:
  level:
    root: info

spring:
  application:
    name: resources-service
  sql:
    init:
      mode: always
  datasource:
    url: ${DB_URL:jdbc:postgresql://localhost:5432/szarvaspc}
    username: ${DB_USERNAME:keycloak}
    password: ${DB_PASSWORD:password}
    driver-class-name: org.postgresql.Driver
  jpa:
    hibernate:
      ddl-auto: update
    properties:
      dialect: org.hibernate.dialect.PostgreSQLDialect
    show-sql: true

eureka:
  instance:
    hostname: localhost
    preferIpAddress: true
    leaseRenewalIntervalInSeconds: 1
    leaseExpirationDurationInSeconds: 2
  client:
    serviceUrl:
      defaultZone: ${EUREKA_SERVER:http://localhost:8761/eureka}
    register-with-eureka: true
    fetch-registry: true
